MyProject_RegularExam/MyProject_RegularExam/Fruitipedia/urls.py
from django.urls import path
from MyProject_RegularExam.Fruitipedia import views

app_name = 'fruitipedia'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('create/', views.create_fruit, name='create_fruit'),
    path('<int:fruit_id>/details/', views.fruit_details, name='fruit_details'),
    path('<int:fruit_id>/edit/', views.edit_fruit, name='edit_fruit'),
    path('<int:fruit_id>/delete/', views.delete_fruit, name='delete_fruit'),
    path('profile/create/', views.create_profile, name='create_profile'),
    path('profile/details/', views.profile_details, name='profile_details'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/delete/', views.delete_profile, name='delete_profile'),
]

MyProject_RegularExam/MyProject_RegularExam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('MyProject_RegularExam.Fruitipedia.urls')),
]

MyProject_RegularExam/MyProject_RegularExam/Fruitipedia/models.py
from django.db import models
"""
You will need 2 models:
    • Profile Model
        ◦ First Name
            ▪ Character field, required.
            ▪ It should consist of a maximum of 25 characters and a minimum of 2 characters.
            ▪ The first name must start with a letter. Otherwise raise ValidationError with the following message: "Your name must start with a letter!"
        ◦ Last Name
            ▪ Character field, required.
            ▪ It should consist of a maximum of 35 characters and a minimum of 1 character.
            ▪ The last name must start with a letter. Otherwise raise ValidationError with the following message: "Your name must start with a letter!"
        ◦ Email
            ▪ Email field, required.
            ▪ It should consist of a maximum of 40 characters.
        ◦ Password
            ▪ Character (password) field, required.
            ▪ It should consist of a maximum of 20 characters and a minimum of 8 characters.
        ◦ Image URL
            ▪ URL field, optional.
        ◦ Age
            ▪ Integer field, optional.
            ▪ The age default value should be 18.

    • Fruit Model
        ◦ Name
            ▪ Character field, required.
            ▪ It should consist of a maximum of 30 and a minimum of 2 characters.
            ▪ The name should contain only letters. Otherwise raise a ValidationError with the following message: "Fruit name should contain only letters!"
        ◦ Image URL
            ▪ URL field, required.
        ◦ Description
            ▪ Text field, required.
        ◦ Nutrition
            ▪ Text field, optional.
"""
# Create your models here.
from django.db import models
from django.core.exceptions import ValidationError


class Profile(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=35)
    email = models.EmailField(max_length=40)
    password = models.CharField(max_length=20)
    image_url = models.URLField(blank=True)
    age = models.IntegerField(default=18)

    def clean(self):
        if not self.first_name[0].isalpha():
            raise ValidationError("Your name must start with a letter!")
        if not self.last_name[0].isalpha():
            raise ValidationError("Your name must start with a letter!")


class Fruit(models.Model):
    name = models.CharField(max_length=30)
    image_url = models.URLField()
    description = models.TextField()
    nutrition = models.TextField(blank=True)

    def clean(self):
        if not self.name.isalpha():
            raise ValidationError("Fruit name should contain only letters!")

MyProject_RegularExam/MyProject_RegularExam/Fruitipedia/views.py
from django.shortcuts import render, redirect
from MyProject_RegularExam.Fruitipedia.models import Profile, Fruit


def index(request):
    return render(request, 'fruitipedia/index.html')


def create_profile(request):
    if request.method == 'POST':
        # Process the profile creation form
        # Save the profile to the database
        return redirect('fruitipedia:dashboard')
    else:
        return render(request, 'fruitipedia/create-profile.html')


def dashboard(request):
    fruits = Fruit.objects.all()
    return render(request, 'fruitipedia/dashboard.html', {'fruits': fruits})


def create_fruit(request):
    if request.method == 'POST':
        # Process the fruit creation form
        # Save the fruit to the database
        return redirect('fruitipedia:dashboard')
    else:
        return render(request, 'fruitipedia/create-fruit.html')


def fruit_details(request, fruit_id):
    fruit = Fruit.objects.get(id=fruit_id)
    return render(request, 'fruitipedia/details-fruit.html', {'fruit': fruit})


def edit_fruit(request, fruit_id):
    fruit = Fruit.objects.get(id=fruit_id)
    if request.method == 'POST':
        # Process the fruit edit form
        # Save the edited fruit to the database
        return redirect('fruitipedia:dashboard')
    else:
        return render(request, 'fruitipedia/edit-fruit.html', {'fruit': fruit})


def delete_fruit(request, fruit_id):
    fruit = Fruit.objects.get(id=fruit_id)
    if request.method == 'POST':
        # Delete the fruit from the database
        return redirect('fruitipedia:dashboard')
    else:
        return render(request, 'fruitipedia/delete-fruit.html', {'fruit': fruit})


def profile_details(request):
    profile = Profile.objects.first()  # Get the profile based on your logic
    return render(request, 'fruitipedia/details-profile.html', {'profile': profile})


def edit_profile(request):
    profile = Profile.objects.first()  # Get the profile based on your logic
    if request.method == 'POST':
        # Process the profile edit form
        # Save the edited profile to the database
        return redirect('fruitipedia:profile_details')
    else:
        return render(request, 'fruitipedia/edit-profile.html', {'profile': profile})


def delete_profile(request):
    profile = Profile.objects.first()  # Get the profile based on your logic
    if request.method == 'POST':
        # Delete the profile and associated fruits from the database
        return redirect('fruitipedia:index')
    else:
        return render(request, 'fruitipedia/delete-profile.html', {'profile': profile})

MyProject_RegularExam/templates/fruitipedia/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}">
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo">
        </a>

        <nav>
            {% block navigation %}
            {% endblock %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/create-fruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>
            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>
        <!-- Add Fruit Form -->
        <section id="create">
            <div class="form">
                <h2>Add Fruit</h2>
                <form class="create-form">
                    <input
                            type="text"
                            name="name"
                            id="name"
                            placeholder="Fruit Name"
                    />
                    <input
                            type="text"
                            name="imageUrl"
                            id="Fruit-image"
                            placeholder="Fruit Image URL"
                    />
                    <textarea
                            id="fruit-description"
                            name="description"
                            placeholder="Fruit Description"
                            rows="10"
                            cols="50"
                    ></textarea>
                    <textarea
                            id="fruit-nutrition"
                            name="nutrition"
                            placeholder="Nutrition Info"
                            rows="10"
                            cols="50"
                    ></textarea>
                    <button type="submit">Add Fruit</button>
                </form>
            </div>
        </section>
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/create-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>
            <!-- If there is a user profile -->
            <div class="user">
                <a href="{% url 'fruitipedia:dashboard' %}">Dashboard</a>
                <a href="{% url 'fruitipedia:create_fruit' %}">Add Fruit</a>
                <a href="{% url 'fruitipedia:profile_details' %}">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                 <a href="{% url 'fruitipedia:create_profile' %}">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>

        <!-- Create Profile Form -->
        <section id="register">
            <div class="form">
                <h2>Create Profile</h2>
                <form class="register-form">
                    <input
                            type="text"
                            name="first-name"
                            id="first-name"
                            placeholder="First Name"
                    />
                    <input
                            type="text"
                            name="last-name"
                            id="last-name"
                            placeholder="Last Name"
                    />
                    <input
                            type="email"
                            name="email"
                            id="register-email"
                            placeholder="Email"
                    />
                    <input
                            type="password"
                            name="password"
                            id="register-password"
                            placeholder="Password"
                    />

                    <button type="submit">Create</button>

                </form>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>

        <!-- Dashboard Page -->
        <h2>Fruits</h2>
        <section id="dashboard">
            <!-- Display a div "fruit" with information about each post (if any)-->

            <!-- first fruit -->
            <div class="fruit">
                <!-- fruit image -->
                <img src="/static/images/fruit 1.png" alt="example1"/>
                <!-- fruit name -->
                <h3 class="title">Pineapple</h3>
                <!-- fruit description -->
                <p class="description">The pineapple is a tropical plant with an edible f...</p>
                <!-- fruit details button -->
                <a class="details-btn" href="#">More Info</a>
            </div>

            <!-- second fruit -->
            <div class="fruit">
                <!-- fruit image -->
                <img src="/static/images/fruit 2.png" alt="example1"/>
                <!-- fruit name -->
                <h3 class="title"> Kiwi</h3>
                <!-- fruit description -->
                <p>Kiwifruit (often shortened to kiwi in North Americ...</p>
                <!-- fruit details button -->
                <a class="details-btn" href="#">More Info</a>
            </div>

            <!-- third fruit -->
            <div class="fruit">
                <!-- fruit image -->
                <img src="/static/images/fruit 3.png" alt="example1"/>
                <!-- fruit name -->
                <h3 class="title">Banana</h3>
                <!-- fruit description -->
                <p>A banana is an elongated, edible fruit – botanical...</p>
                <!-- fruit details button -->
                <a class="details-btn" href="#">More Info</a>
            </div>

        </section>

        <!-- Display a heading if there are no posts -->
        <h2>No fruit info yet.</h2>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/delete-fruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>

        <!-- Delete Fruit Form -->
        <section id="edit">
            
                <div class="form">
                    <h2>Delete Fruit</h2>
                    <form class="edit-form">
                        <label for="name">Name:</label>
                        <input
                                type="text"
                                name="name"
                                id="name"
                                value="Pineapple"
                                disabled="disabled" readonly="readonly" required=""
                        />
                        <label for="Fruit-image">Image URL:</label>
                        <input
                                type="url"
                                name="imageUrl"
                                id="Fruit-image"
                                value="https://pineapple-fruit-image.jpeg"
                                disabled="disabled" readonly="readonly" required=""
                        />
                        <label for="fruit-description">Description:</label>
                        <textarea
                                id="fruit-description"
                                name="description"
                                rows="10"
                                cols="50"
                                disabled="disabled" readonly="readonly" required=""
                        >The pineapple is a tropical plant with an edible fruit. It is the most economically significant plant in the family Bromeliaceae. The pineapple is indigenous to South America. Pineapples grow as a small shrub, the individual flowers of the unpollinated plant fuse to form a multiple fruit. The plant is normally propagated from the offset produced at the top of the fruit, or from a side shoot, and typically matures within a year.</textarea>

                        <button type="submit">Delete</button>
                    </form>
                </div>
           
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/delete-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If no user profile has been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>

        <section id="edit">

            <div class="form">
                <h1>Are you sure you want to delete your profile?</h1>
                
                <!-- Delete Profile Form -->
                <form id='delete' class="register-form">
                    <!-- Confirm Button -->
                    <button type="submit">Yes</button>

                </form>
                <!-- End Delete Profile Form -->
            </div>
            
        </section>
    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/details-fruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>

        <!-- Fruit Details -->
        <section id="details">
            <div id="details-wrapper">
                <!-- fruit image -->
                <img id="details-img" src="/static/images/fruit 1.png" alt="example1"/>
                <!-- fruit name -->
                <p id="details-title">Pineapple</p>
                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- fruit description -->
                        <p>
                            The pineapple is a tropical plant with an edible fruit.
                            It is the most economically significant plant in the family Bromeliaceae.The
                            pineapple is indigenous to South America.
                            Pineapples grow as a small shrub, the individual flowers of the unpollinated plant
                            fuse to form a multiple fruit. The plant is normally propagated from the offset produced
                            at the top of the fruit,or from a side shoot, and typically matures within a year.
                        </p>
                        <!-- fruit nutrition -->
                        <p id="nutrition">Nutrition</p>
                        <!-- fruit nutrition details -->
                        <p id="details-nutrition">
                            Raw pineapple pulp is 86% water, 13% carbohydrates, 0.5% protein, and contains negligible
                            fat (table).
                            In a 100-gram reference amount, raw pineapple supplies 209 kilojoules (50 kilocalories) of
                            food energy,
                            and is a rich source of manganese (44% Daily Value, DV) and vitamin C (58% DV), but
                            otherwise contains
                            no micronutrients in significant amounts.
                        </p>
                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="#" id="edit-btn">Edit</a>
                        <a href="#" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/details-profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>

        </nav>
    </header>

    <main>

        <!-- Profile Details Section -->

        <section id="details">
            <div id="details-wrapper">
                <h2>Profile Details</h2>
                <!-- if the user has a profile image -->
                <img id="details-img" src="https://images.pexels.com/photos/3792581/pexels-photo-3792581.jpeg"
                     alt="profile img"/>

                <!-- if the user has NO profile image -->
                <img id="details-img" src="/static/images/default.jpg" alt="profile img"/>

                <!-- user's full name -->
                <p id="details-title">Mariya Petrova</p>

                <div id="info-wrapper">
                    <div id="details-description">
                        <!-- email -->
                        <p>
                            mariya@abv.bg
                        </p>
                        <!-- age -->
                        <p>
                            Age: 18
                        </p>
                        <!-- number of posts -->
                        <p id="nutrition">Posts: 3</p>

                    </div>

                    <!--Edit and Delete buttons -->
                    <div id="action-buttons">
                        <a href="#" id="edit-btn">Edit</a>
                        <a href="#" id="delete-btn">Delete</a>
                    </div>
                </div>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/edit-fruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
    <link rel="stylesheet" href="/static/styles/styles.css"/>
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
            <img id="logo-img" src="/static/images/logo.png" alt="logo"/>
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="#">Dashboard</a>
                <a href="#">Add Fruit</a>
                <a href="#">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                <a href="#">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>

        <!-- Edit Fruit Form -->
        <section id="edit">
            <div class="form">
                <h2>Edit Fruit</h2>
                <form class="edit-form">
                    <label for="name">Name:</label>
                    <input
                            type="text"
                            name="name"
                            id="name"
                            value="Pineapple"
                    />
                    <label for="Fruit-image">Image URL:</label>
                    <input
                            type="url"
                            name="imageUrl"
                            id="Fruit-image"
                            value="https://some-pineapple-fruit-image.jpeg"
                    />
                    <label for="fruit-description">Description:</label>
                    <textarea
                            id="fruit-description"
                            name="description"
                            rows="10"
                            cols="50"
                    >The pineapple is a tropical plant with an edible fruit. It is the most economically significant plant in the family Bromeliaceae. The pineapple is indigenous to South America. Pineapples grow as a small shrub, the individual flowers of the unpollinated plant fuse to form a multiple fruit. The plant is normally propagated from the offset produced at the top of the fruit, or from a side shoot, and typically matures within a year.</textarea>
                    <label for="fruit-nutrition">Nutrition:</label>
                    <textarea
                            id="fruit-nutrition"
                            name="nutrition"
                            rows="10"
                            cols="50"
                    >Raw pineapple pulp is 86% water, 13% carbohydrates, 0.5% protein, and contains negligible fat (table). In a 100-gram reference amount, raw pineapple supplies 209 kilojoules (50 kilocalories) of food energy, and is a rich source of manganese (44% Daily Value, DV) and vitamin C (58% DV), but otherwise contains no micronutrients in significant amounts.</textarea>

                    <button type="submit">Edit</button>
                </form>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
<footer>
    <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
</footer>
</body>
</html>

MyProject_RegularExam/templates/fruitipedia/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=\, initial-scale=1.0"/>
<link rel="stylesheet" type="text/css" href="{% static 'styles/styles.css' %}">
    <title>Fruitipedia</title>
</head>
<body>
<div id="wrapper">
    <header>
        <!-- Navigation -->
        <a id="logo" href="#">
<img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo">
        </a>

        <nav>

            <!-- If there is a user profile -->
            <div class="user">
                <a href="{% url 'fruitipedia:dashboard' %}">Dashboard</a>
                <a href="{% url 'fruitipedia:create_fruit' %}">Add Fruit</a>
                <a href="{% url 'fruitipedia:profile_details' %}">Profile</a>
            </div>

            <!-- If user profile has NOT been created -->
            <div class="guest">

                 <a href="{% url 'fruitipedia:create_profile' %}">Create Profile</a>

            </div>
        </nav>
    </header>

    <main>
        <!-- Home page -->
        <section id="home">
          <h1>Learn more about your favorite fruits</h1>
<img src="{% static 'images/pexels-pixabay-161559-dImkWBDHz-transformed (1).png' %}" alt="home">


        </section>

      </main>
    </div>
<!-- footer -->
    <footer>
      <p>@Fruitipedia - SoftUni Team 2023. All rights reserved.</p>
    </footer>
  </body>
</html>